//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engzli.Fard.Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class fm_health
    {
        public int id { get; set; }
        public int fid { get; set; }
        public int health_diabetes_st1 { get; set; }
        public int health_diabetes_st2 { get; set; }
        public int health_bloodpresure { get; set; }
        public int health_cv { get; set; }
        public int health_epilipce { get; set; }
        public int health_asthma { get; set; }
        public int health_gland { get; set; }
        public int health_tuamer_st1 { get; set; }
        public int health_tuamer_st2 { get; set; }
        public int health_anima { get; set; }
        public int health_disability_st1 { get; set; }
        public int health_disability_st2 { get; set; }
        public int health_disability_st3 { get; set; }
        public int health_surgry { get; set; }
        public int health_disease_st1 { get; set; }
        public int health_disease_st2 { get; set; }
        public int health_disease_st3 { get; set; }
        public int health_disease_st4 { get; set; }
        public int health_disease_st5 { get; set; }
        public int health_disease_st6 { get; set; }
        public int health_med_care { get; set; }
        public int health_xray { get; set; }
        public int health_med_tests { get; set; }
        public string health_medicine { get; set; }
        public string note { get; set; }
    
        public virtual fm fm { get; set; }
    }
}
