//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engzli.Fard.Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class fm_study_work
    {
        public int id { get; set; }
        public int fid { get; set; }
        public int fm_study_work_st { get; set; }
        public string fm_study_work_level { get; set; }
        public string fm_study_work_skills { get; set; }
        public int fm_study_work_ability { get; set; }
        public int fm_study_work_workeg { get; set; }
        public int fm_study_work_notegreg { get; set; }
        public string fm_study_work_reg { get; set; }
        public string fm_study_work_reg_soc_school { get; set; }
    
        public virtual fm fm { get; set; }
    }
}
