//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engzli.Fard.Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class org_visitors
    {
        public int id { get; set; }
        public string name { get; set; }
        public int people { get; set; }
        public int rooms_count { get; set; }
        public Nullable<System.DateTime> datetime_start { get; set; }
        public Nullable<System.DateTime> datetime_end { get; set; }
        public string note { get; set; }
        public string addedby { get; set; }
        public Nullable<System.DateTime> addeddatetime { get; set; }
        public string editedby { get; set; }
        public Nullable<System.DateTime> editeddatetime { get; set; }
    }
}
