//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engzli.Fard.Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class problems_reports
    {
        public int id { get; set; }
        public string problem { get; set; }
        public string addedby { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string time { get; set; }
    }
}
