//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engzli.Fard.Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class provider_house_assest
    {
        public int id { get; set; }
        public Nullable<int> fid { get; set; }
        public int house_assest_bed { get; set; }
        public int house_assest_tv { get; set; }
        public int house_assest_fan { get; set; }
        public int house_assest_blanket { get; set; }
        public int house_assest_waterheater { get; set; }
        public int house_assest_washer { get; set; }
        public int house_assest_ref { get; set; }
        public int house_assest_oven { get; set; }
        public int house_assest_carpet { get; set; }
        public int house_assest_gas { get; set; }
        public int house_assest_mrtba { get; set; }
        public string house_assest_other { get; set; }
        public string notes { get; set; }
    
        public virtual provider provider { get; set; }
    }
}
