//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engzli.Fard.Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class provider_study_work
    {
        public int id { get; set; }
        public Nullable<int> fid { get; set; }
        public int study_work_st { get; set; }
        public string study_work_level { get; set; }
        public string study_work_skills { get; set; }
        public int study_work_ability { get; set; }
        public int study_work_workeg { get; set; }
    
        public virtual provider provider { get; set; }
    }
}
