//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engzli.Fard.Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class provider_researcher
    {
        public int id { get; set; }
        public Nullable<int> fid { get; set; }
        public string researcher_cat { get; set; }
        public string researcher_phone { get; set; }
        public string researcher_name { get; set; }
        public string field_researcher_phone { get; set; }
        public string field_researcher_name { get; set; }
        public Nullable<System.DateTime> researcher_date { get; set; }
        public string researcher_place { get; set; }
    
        public virtual provider provider { get; set; }
    }
}
