//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engzli.Fard.Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class provider_family_needs
    {
        public int id { get; set; }
        public Nullable<int> fid { get; set; }
        public int family_needs_st1 { get; set; }
        public int family_needs_st2 { get; set; }
        public int family_needs_st3 { get; set; }
        public int family_needs_st4 { get; set; }
        public int family_needs_st5 { get; set; }
        public int family_needs_st6 { get; set; }
        public string notes { get; set; }
    
        public virtual provider provider { get; set; }
    }
}
