//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engzli.Fard.Entities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public provider()
        {
            this.fms = new HashSet<fm>();
            this.provider_associations = new HashSet<provider_associations>();
            this.provider_distrbution = new HashSet<provider_distrbution>();
            this.provider_family_needs = new HashSet<provider_family_needs>();
            this.provider_health = new HashSet<provider_health>();
            this.provider_house_assest = new HashSet<provider_house_assest>();
            this.provider_income_eg = new HashSet<provider_income_eg>();
            this.provider_passport = new HashSet<provider_passport>();
            this.provider_researcher = new HashSet<provider_researcher>();
            this.provider_residence = new HashSet<provider_residence>();
            this.provider_study_work = new HashSet<provider_study_work>();
        }
    
        public int id { get; set; }
        public int provider_uid { get; set; }
        public string provider_name { get; set; }
        public string provider_phone { get; set; }
        public string provider_phone2 { get; set; }
        public string provider_yellowcard { get; set; }
        public int provider_un_reg { get; set; }
        public int provider_family { get; set; }
        public int provider_livealone { get; set; }
        public int provider_traveled { get; set; }
        public int provider_visited { get; set; }
        public int orphan { get; set; }
        public string note { get; set; }
        public string addby { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
        public string addtime { get; set; }
        public string editedby { get; set; }
        public Nullable<System.DateTime> editeddate { get; set; }
        public string editedtime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fm> fms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<provider_associations> provider_associations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<provider_distrbution> provider_distrbution { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<provider_family_needs> provider_family_needs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<provider_health> provider_health { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<provider_house_assest> provider_house_assest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<provider_income_eg> provider_income_eg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<provider_passport> provider_passport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<provider_researcher> provider_researcher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<provider_residence> provider_residence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<provider_study_work> provider_study_work { get; set; }
    }
}
